import { geistSans, geistMono } from "@fonts";
import "@styles/globals.css";
import type { Metadata } from "next";
import { ReactNode } from "react";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

/**
 * RootLayout is the root layout component for the application.
 * It wraps all pages with the base HTML and body structure, and provides font and CSS classes.
 *
 * @param children - The React node(s) to render within the layout.
 * @returns The root HTML layout for the app.
 */
export default function RootLayout({ children }: Readonly<{ children: ReactNode }>) {
    return (
        <html lang="en">
            <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>{children}</body>
        </html>
    );
}
